# ============================================================
# DEFAULT
server:
  port: 8088
  forward-headers-strategy: framework
  error:
    include-message: always
  servlet:
    session:
      cookie:
        secure: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd'T'HH:mm:ss}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx{${LOG_STACKTRACE_LIMIT:1}}}"
  level:
    org:
      hibernate:
        sql: debug

spring:
  application:
    name: fundamental-engine
  profiles:
    default: local
    active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/fundamental-engine
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 5

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  management:
    tracing:
      sampling:
        probability: 1.0

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    syntaxHighlight:
      theme: "monokai"

log4j:
  logger:
    org:
      hibernate: WARN

---
# ============================================================
# LOCAL
spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# ============================================================
# DEV
spring:
  config:
    activate:
      on-profile: dev

---
# ============================================================
# PROD
spring:
  config:
    activate:
      on-profile: prod
